name: kundenberatung
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^0.3.9  #Fonts
  cupertino_icons: ^0.1.3  #Icons
  dio: ^3.0.10   #Networking
#  shared_preferences: ^0.5.10   #local storage
  carousel_slider: ^2.2.1
  circular_check_box: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
   - assets/images/ic_background_opacity.jpeg
   - assets/images/ic_background.jpeg
   - assets/images/ic_menu.png
   - assets/images/img_sample1.png
   - assets/images/img_sample2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

